### ISSUE TITLE
🐛 BUG: Can't run loop inside ${} inside {`<style><style>`}

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/compiler#222]
### What version of `@astrojs/compiler` are you using?

0.5.7

### What package manager are you using?

yarn

### What operating system are you using?

Ubuntu

### Describe the Bug

Can't loop/map over an array inside **{`<style><style>`}**. It outputs the following error:

![image](https://user-images.githubusercontent.com/63650415/146063287-c2021bab-e27f-4e06-aacc-beec4363be9c.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vzgf3w?file=src%2Fpages%2Findex.astro

**Comment by FredKSchott** [comment]
FYI adding a style tag dynamically like this (inside of a `{}`) isn't really supported. We just accepted an RFC to finalize what is and isn't supported.

You can use `define:vars` to support this though!

```
<style define:vars={{height: 10, width: 10}}>
  // ...
  height: var(--height);
  width: var(--width);
</style>

**Comment by RafidMuhymin** [comment]
@FredKSchott Why not just treat style tags inside backticks like this {\`<style></style>\`} just like any other tags as pure string??

**Comment by FredKSchott** [comment]
+1, I believe we are moving that direction in the future with https://github.com/withastro/rfcs/pull/41 where this would be supported but just treated as any other element in the template, like you said.

I'll leave this open for now, even if this isn't really supported yet. On second though, this bug will probably (hopefully!) be fixed by https://github.com/withastro/astro/pull/2168

**Comment by natemoo-re** [comment]
Looks like this is throwing because it's invalid code.

```js
{`<style>
  ${[height, width].map(size => `
    .container-${size} {
      height: ${size}px;
      width: ${size}px;
    }
</style>`}
```

The correct code is below and I've verified that it's working as expected in the compiler.
 
```js
{`<style>
  ${[height, width].map(size => `
    .container-${size} {
      height: ${size}px;
      width: ${size}px;
    }`).join('\n')
  }
</style>`}
```

**Comment by RafidMuhymin** [comment]
@natemoo-re I just updated the StackBlitz repro using your code. But I'm still getting the error. I have tried after upgrading to v0.22.1 also.
